import { dataCy } from "../support/utils";

export const AMAZON_CONSTATNS = Object.freeze({
  amazonURL: "https://www.amazon.com/",
  amazonLogo: "#nav-logo-sprites",
  amazonGreetingMessageText: "#glow-ingress-line1",
  amazonSearchBox: "#twotabsearchtextbox",
  amazonSearchButton: "#nav-search-submit-button",
  amazonProductName: "Sweater",
  amazonResultText: "RESULTS",
  amazonBestSellerItemsBadgeText: "Best Seller",
  amazonProductResultList: ".s-image-padding",
  amazonProductMediumSizeFilter: "#a-autoid-5-announce",
  amazonProductTodaysDealFilterText: "Today's Deals",
  amazonAddtoCartButton: "#add-to-cart-button",
  amazonAddedToChartMessage: "Added to Cart",
  amazonProccedToCheckoutBtn: "#desktop-ptc-button-celWidget",
  amazonSignInHeader: ".a-spacing-small",
  amazonSignInUserNamelBox: "#ap_email",
  amazonSignInPasswordBox: "#ap_password",
  amazonEmailAddress: "Test@test.com",
  amazonEmailPassword: "testing",
  amazonContinueBtn: "#continue",
  amazonSignInBtn: "#signInSubmit",
  amazonSignInErrorText: "Enter your email or mobile phone number",
  amazonPasswordErrorText: "Enter your password",
  amazonAuthErrorMessage: "#auth-error-message-box",
  amazonLogoLink: ".a-link-nav-icon",
  amazonChartCount: "#nav-cart-count",
});
